// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ActiveHouseholdResponse = {
    householdId: null | number;
    role: null | HouseholdRole;
    hasActiveHousehold: boolean;
};

export type AddMemberRequest = {
    email: string;
    role: null | HouseholdRole;
};

export type ApplyBlueprintRequest = {
    blueprintId: number;
};

export type AttachmentType = 'Image' | 'Document';

export type CopyEntry = {
    recipeItemId: number;
    quantity: null | QuantityDto;
};

export type CopyRecipeToListRequest = {
    targetListId: number;
    items: Array<CopyEntry>;
};

export type CopyRecipeToListResponse = {
    copiedCount: number;
};

export type CreateBlueprintRequest = {
    name: string;
    categories: Array<ProductCategory>;
};

export type CreateHouseholdRequest = {
    name: string;
    description: null | string;
};

export type CreateInventoryItemRequest = {
    text: string;
    quantity: null | QuantityDto;
    expiryDate: null | string;
};

export type CreateInventoryRequest = {
    name: string;
    description: null | string;
};

export type CreateItemRequest = {
    text: string;
    comment: null | string;
    quantity?: null | QuantityDto;
};

export type CreateListRequest = {
    name: string;
    description: null | string;
};

export type CreateRecipeItemRequest = {
    sectionId: number;
    text: string;
    comment: null | string;
};

export type CreateRecipeLinkRequest = {
    url: string;
    label: null | string;
};

export type CreateRecipeRequest = {
    name: string;
    description: null | string;
    servings: null | number;
};

export type CreateRecipeSectionRequest = {
    name: null | string;
    description: null | string;
};

export type ExpiryCalendarItemResponse = {
    id: number;
    inventoryId: number;
    inventoryName: string;
    text: string;
    quantity: null | QuantityDto;
    expiryDate: string;
};

export type ExpiryHandling = 'Unknown' | 'NonPerishable' | 'UserEntersFromPackage' | 'AiRecommendsShelfLife';

export type HouseholdResponse = {
    id: number;
    name: string;
    description: null | string;
    createdAt: string;
    updatedAt: string;
    createdByUserId: string;
    currentUserRole: HouseholdRole;
};

export type HouseholdRole = 'Member' | 'Admin' | 'Owner';

export type HouseholdSettingsResponse = {
    checkedItemRetentionDays: number;
};

export type HttpValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
    errors: {
        [key: string]: Array<string>;
    };
};

export type IFormFile = Blob | File;

export type InventoryCreatorResponse = {
    externalId: string;
    name: string;
    email: null | string;
};

export type InventoryItemResponse = {
    id: number;
    inventoryId: number;
    text: string;
    quantity: null | QuantityDto;
    expiryDate: null | string;
    rank: string;
    createdAt: string;
    updatedAt: string;
    isExpiring: boolean;
};

export type InventoryResponse = {
    id: number;
    name: string;
    description: null | string;
    householdId: number;
    createdAt: string;
    updatedAt: string;
    createdByUser: InventoryCreatorResponse;
    totalItems: number;
    expiringItems: number;
    earliestExpiryDate: null | string;
};

export type InventorySettingsResponse = {
    [key: string]: unknown;
};

export type ListCreatorResponse = {
    externalId: string;
    name: string;
    email: null | string;
};

export type ListItemResponse = {
    id: number;
    listId: number;
    text: string;
    comment: null | string;
    quantity: null | QuantityDto;
    status: boolean;
    rank: string;
    createdAt: string;
    updatedAt: string;
    type: ListItemType;
    fileName?: null | string;
    contentType?: null | string;
    fileSize?: null | number;
    extractionPending: boolean;
    promote?: null | PromoteSuggestion;
};

export type ListItemType = 'Text' | 'Image' | 'Document';

export type ListResponse = {
    id: number;
    name: string;
    description: null | string;
    householdId: number;
    createdAt: string;
    updatedAt: string;
    createdByUser: ListCreatorResponse;
    uncheckedCount: number;
    checkedCount: number;
    pendingPromotionCount: number;
};

export type MemberResponse = {
    externalId: string;
    name: string;
    email: string;
    role: HouseholdRole;
    joinedAt: string;
};

export type MyInventoryNotificationResponse = {
    enabled: boolean;
    leadDays: null | number;
};

export type OverrideProductClassificationRequest = {
    category: ProductCategory;
    expiryHandling: ExpiryHandling;
    shelfLifeDays: null | number;
};

export type PendingPromotionResponse = {
    listItemId: number;
    text: string;
    quantity: null | QuantityDto;
    expiryHandling: ExpiryHandling;
    suggestedExpiry: null | string;
};

export type ProductCatalogItem = {
    id: number;
    name: string;
    effectiveCategory: ProductCategory;
    effectiveExpiryHandling: ExpiryHandling;
    effectiveShelfLifeDays: null | number;
    isOverridden: boolean;
    aiCategory: ProductCategory;
    aiExpiryHandling: ExpiryHandling;
    aiShelfLifeDays: null | number;
};

export type ProductCategory = 'Unknown' | 'Other' | 'Produce' | 'Bakery' | 'Meat' | 'Fish' | 'DairyAndEggs' | 'Cheese' | 'DeliAndColdCuts' | 'Frozen' | 'Pantry' | 'CannedGoods' | 'Sauces' | 'OilsAndVinegar' | 'Spices' | 'Cereal' | 'Spreads' | 'Snacks' | 'Sweets' | 'Beverages' | 'Alcohol' | 'HouseholdAndCleaning' | 'HealthAndBeauty' | 'Baby' | 'Pet';

export type PromoteEntry = {
    listItemId: number;
    quantity: null | QuantityDto;
    expiryDate: null | string;
};

export type PromoteListItemsRequest = {
    inventoryId: number;
    items: Array<PromoteEntry>;
};

export type PromoteListItemsResponse = {
    promotedCount: number;
};

export type PromoteSuggestion = {
    expiryHandling: ExpiryHandling;
    suggestedExpiry: null | string;
};

export type QuantityDto = {
    value: number | string;
    unit: QuantityUnit;
};

export type QuantityUnit = 'Gram' | 'Kilogram' | 'Milliliter' | 'Liter' | 'Piece' | 'Pack' | 'Can' | 'Bottle' | 'Bag';

export type RecipeAttachmentResponse = {
    id: number;
    recipeId: number;
    type: AttachmentType;
    contentType: string;
    originalFileName: null | string;
    fileSizeBytes: number;
    caption: null | string;
    rank: string;
    createdAt: string;
    updatedAt: string;
};

export type RecipeCreatorResponse = {
    externalId: string;
    name: string;
    email: null | string;
};

export type RecipeItemResponse = {
    id: number;
    recipeId: number;
    sectionId: number;
    text: string;
    comment: null | string;
    quantity: null | QuantityDto;
    rank: string;
    createdAt: string;
    updatedAt: string;
    extractionPending: boolean;
};

export type RecipeLinkResponse = {
    id: number;
    recipeId: number;
    url: string;
    label: null | string;
    rank: string;
    createdAt: string;
    updatedAt: string;
};

export type RecipeResponse = {
    id: number;
    name: string;
    description: null | string;
    servings: null | number;
    householdId: number;
    createdAt: string;
    updatedAt: string;
    createdByUser: RecipeCreatorResponse;
    itemCount: number;
    coverAttachmentId: null | number;
    ingredients: Array<string>;
    tags: Array<RecipeTag>;
};

export type RecipeSectionResponse = {
    id: number;
    recipeId: number;
    name: null | string;
    description: null | string;
    rank: string;
    createdAt: string;
    updatedAt: string;
};

export type RecipeTag = 'Breakfast' | 'Starter' | 'Main' | 'Side' | 'Salad' | 'Soup' | 'Dessert' | 'Snack' | 'Drink' | 'Sauce' | 'Baking' | 'Bread' | 'Vegetarian' | 'Vegan' | 'GlutenFree' | 'DairyFree' | 'LactoseFree' | 'LowCarb';

export type RegisterFcmTokenRequest = {
    token: string;
};

export type ReorderItemRequest = {
    afterId: number;
};

export type RevisionResponse = {
    rev: string;
};

export type SetActiveHouseholdRequest = {
    householdId: number;
};

export type SetRecipeTagsRequest = {
    tags: Array<RecipeTag>;
};

export type SkipPromotionRequest = {
    listItemIds: Array<number>;
};

export type SortBlueprintResponse = {
    id: number;
    name: string;
    categories: Array<ProductCategory>;
};

export type SuggestRecipeTagsResponse = {
    suggestedTags: Array<RecipeTag>;
};

export type UpdateBlueprintRequest = {
    name: string;
    categories: Array<ProductCategory>;
};

export type UpdateHouseholdSettingsRequest = {
    checkedItemRetentionDays: number;
};

export type UpdateInventoryItemRequest = {
    text: null | string;
    quantity: null | QuantityDto;
    clearQuantity: null | boolean;
    expiryDate: null | string;
};

export type UpdateInventoryRequest = {
    name: string;
    description: null | string;
};

export type UpdateInventorySettingsRequest = {
    [key: string]: unknown;
};

export type UpdateItemRequest = {
    text: null | string;
    quantity: null | QuantityDto;
    clearQuantity: null | boolean;
    status: null | boolean;
    comment: null | string;
};

export type UpdateListRequest = {
    name: string;
    description: null | string;
};

export type UpdateMemberRoleRequest = {
    role: HouseholdRole;
};

export type UpdateMyInventoryNotificationRequest = {
    enabled: boolean;
    leadDays: null | number;
};

export type UpdateProfileRequest = {
    name: string;
};

export type UpdateRecipeAttachmentRequest = {
    caption: null | string;
};

export type UpdateRecipeItemRequest = {
    text: null | string;
    quantity: null | QuantityDto;
    clearQuantity: null | boolean;
    comment: null | string;
};

export type UpdateRecipeLinkRequest = {
    url: string;
    label: null | string;
};

export type UpdateRecipeRequest = {
    name: string;
    description: null | string;
    servings: null | number;
};

export type UpdateRecipeSectionRequest = {
    name: null | string;
    description: null | string;
};

export type UpdateUserNotificationSettingsRequest = {
    expiryNotificationsEnabled: boolean;
    expiryLeadDays: number;
};

export type UpdateUserSettingsRequest = {
    language: null | string;
};

export type UserSettingsResponse = {
    language: null | string;
    expiryNotificationsEnabled: boolean;
    expiryLeadDays: number;
};

export type WeatherForecast = {
    date: string;
    temperatureC: number;
    temperatureF: number;
    summary?: null | string;
};

export type GetUserHouseholdsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/household';
};

export type GetUserHouseholdsResponses = {
    /**
     * OK
     */
    200: Array<HouseholdResponse>;
};

export type GetUserHouseholdsResponse = GetUserHouseholdsResponses[keyof GetUserHouseholdsResponses];

export type CreateHouseholdData = {
    body: CreateHouseholdRequest;
    path?: never;
    query?: never;
    url: '/api/household';
};

export type CreateHouseholdErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type CreateHouseholdError = CreateHouseholdErrors[keyof CreateHouseholdErrors];

export type CreateHouseholdResponses = {
    /**
     * Created
     */
    201: HouseholdResponse;
};

export type CreateHouseholdResponse = CreateHouseholdResponses[keyof CreateHouseholdResponses];

export type DeleteHouseholdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/household/{id}';
};

export type DeleteHouseholdErrors = {
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteHouseholdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteHouseholdResponse = DeleteHouseholdResponses[keyof DeleteHouseholdResponses];

export type GetMembersData = {
    body?: never;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/members';
};

export type GetMembersErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMembersResponses = {
    /**
     * OK
     */
    200: Array<MemberResponse>;
};

export type GetMembersResponse = GetMembersResponses[keyof GetMembersResponses];

export type AddMemberData = {
    body: AddMemberRequest;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/members';
};

export type AddMemberErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type AddMemberError = AddMemberErrors[keyof AddMemberErrors];

export type AddMemberResponses = {
    /**
     * Created
     */
    201: MemberResponse;
};

export type AddMemberResponse = AddMemberResponses[keyof AddMemberResponses];

export type RemoveMemberData = {
    body?: never;
    path: {
        householdId: number;
        userId: string;
    };
    query?: never;
    url: '/api/household/{householdId}/members/{userId}';
};

export type RemoveMemberErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type RemoveMemberError = RemoveMemberErrors[keyof RemoveMemberErrors];

export type RemoveMemberResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveMemberResponse = RemoveMemberResponses[keyof RemoveMemberResponses];

export type UpdateMemberRoleData = {
    body: UpdateMemberRoleRequest;
    path: {
        householdId: number;
        userId: string;
    };
    query?: never;
    url: '/api/household/{householdId}/members/{userId}/role';
};

export type UpdateMemberRoleErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateMemberRoleError = UpdateMemberRoleErrors[keyof UpdateMemberRoleErrors];

export type UpdateMemberRoleResponses = {
    /**
     * OK
     */
    200: MemberResponse;
};

export type UpdateMemberRoleResponse = UpdateMemberRoleResponses[keyof UpdateMemberRoleResponses];

export type GetHouseholdSettingsData = {
    body?: never;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/settings';
};

export type GetHouseholdSettingsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetHouseholdSettingsResponses = {
    /**
     * OK
     */
    200: HouseholdSettingsResponse;
};

export type GetHouseholdSettingsResponse = GetHouseholdSettingsResponses[keyof GetHouseholdSettingsResponses];

export type UpdateHouseholdSettingsData = {
    body: UpdateHouseholdSettingsRequest;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/settings';
};

export type UpdateHouseholdSettingsErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateHouseholdSettingsError = UpdateHouseholdSettingsErrors[keyof UpdateHouseholdSettingsErrors];

export type UpdateHouseholdSettingsResponses = {
    /**
     * OK
     */
    200: HouseholdSettingsResponse;
};

export type UpdateHouseholdSettingsResponse = UpdateHouseholdSettingsResponses[keyof UpdateHouseholdSettingsResponses];

export type GetProductsData = {
    body?: never;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/products';
};

export type GetProductsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetProductsResponses = {
    /**
     * OK
     */
    200: Array<ProductCatalogItem>;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type ResetProductClassificationData = {
    body?: never;
    path: {
        householdId: number;
        productId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/products/{productId}/classification';
};

export type ResetProductClassificationErrors = {
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type ResetProductClassificationResponses = {
    /**
     * OK
     */
    200: ProductCatalogItem;
};

export type ResetProductClassificationResponse = ResetProductClassificationResponses[keyof ResetProductClassificationResponses];

export type OverrideProductClassificationData = {
    body: OverrideProductClassificationRequest;
    path: {
        householdId: number;
        productId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/products/{productId}/classification';
};

export type OverrideProductClassificationErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type OverrideProductClassificationError = OverrideProductClassificationErrors[keyof OverrideProductClassificationErrors];

export type OverrideProductClassificationResponses = {
    /**
     * OK
     */
    200: ProductCatalogItem;
};

export type OverrideProductClassificationResponse = OverrideProductClassificationResponses[keyof OverrideProductClassificationResponses];

export type GetBlueprintsData = {
    body?: never;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/blueprints';
};

export type GetBlueprintsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetBlueprintsResponses = {
    /**
     * OK
     */
    200: Array<SortBlueprintResponse>;
};

export type GetBlueprintsResponse = GetBlueprintsResponses[keyof GetBlueprintsResponses];

export type CreateBlueprintData = {
    body: CreateBlueprintRequest;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/blueprints';
};

export type CreateBlueprintErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateBlueprintError = CreateBlueprintErrors[keyof CreateBlueprintErrors];

export type CreateBlueprintResponses = {
    /**
     * OK
     */
    200: SortBlueprintResponse;
};

export type CreateBlueprintResponse = CreateBlueprintResponses[keyof CreateBlueprintResponses];

export type DeleteBlueprintData = {
    body?: never;
    path: {
        householdId: number;
        blueprintId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/blueprints/{blueprintId}';
};

export type DeleteBlueprintErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteBlueprintResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteBlueprintResponse = DeleteBlueprintResponses[keyof DeleteBlueprintResponses];

export type GetBlueprintData = {
    body?: never;
    path: {
        householdId: number;
        blueprintId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/blueprints/{blueprintId}';
};

export type GetBlueprintErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetBlueprintResponses = {
    /**
     * OK
     */
    200: SortBlueprintResponse;
};

export type GetBlueprintResponse = GetBlueprintResponses[keyof GetBlueprintResponses];

export type UpdateBlueprintData = {
    body: UpdateBlueprintRequest;
    path: {
        householdId: number;
        blueprintId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/blueprints/{blueprintId}';
};

export type UpdateBlueprintErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateBlueprintError = UpdateBlueprintErrors[keyof UpdateBlueprintErrors];

export type UpdateBlueprintResponses = {
    /**
     * OK
     */
    200: SortBlueprintResponse;
};

export type UpdateBlueprintResponse = UpdateBlueprintResponses[keyof UpdateBlueprintResponses];

export type RestoreBlueprintData = {
    body?: never;
    path: {
        householdId: number;
        blueprintId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/blueprints/{blueprintId}/restore';
};

export type RestoreBlueprintErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type RestoreBlueprintResponses = {
    /**
     * OK
     */
    200: SortBlueprintResponse;
};

export type RestoreBlueprintResponse = RestoreBlueprintResponses[keyof RestoreBlueprintResponses];

export type GetListsData = {
    body?: never;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists';
};

export type GetListsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetListsResponses = {
    /**
     * OK
     */
    200: Array<ListResponse>;
};

export type GetListsResponse = GetListsResponses[keyof GetListsResponses];

export type CreateListData = {
    body: CreateListRequest;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists';
};

export type CreateListErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateListError = CreateListErrors[keyof CreateListErrors];

export type CreateListResponses = {
    /**
     * Created
     */
    201: ListResponse;
};

export type CreateListResponse = CreateListResponses[keyof CreateListResponses];

export type DeleteListData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}';
};

export type DeleteListErrors = {
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteListResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteListResponse = DeleteListResponses[keyof DeleteListResponses];

export type GetListData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}';
};

export type GetListErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetListResponses = {
    /**
     * OK
     */
    200: ListResponse;
};

export type GetListResponse = GetListResponses[keyof GetListResponses];

export type UpdateListData = {
    body: UpdateListRequest;
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}';
};

export type UpdateListErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateListError = UpdateListErrors[keyof UpdateListErrors];

export type UpdateListResponses = {
    /**
     * OK
     */
    200: ListResponse;
};

export type UpdateListResponse = UpdateListResponses[keyof UpdateListResponses];

export type GetPendingPromotionsData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/pending-promotions';
};

export type GetPendingPromotionsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetPendingPromotionsResponses = {
    /**
     * OK
     */
    200: Array<PendingPromotionResponse>;
};

export type GetPendingPromotionsResponse = GetPendingPromotionsResponses[keyof GetPendingPromotionsResponses];

export type PromoteListItemsData = {
    body: PromoteListItemsRequest;
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/promote';
};

export type PromoteListItemsErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PromoteListItemsError = PromoteListItemsErrors[keyof PromoteListItemsErrors];

export type PromoteListItemsResponses = {
    /**
     * OK
     */
    200: PromoteListItemsResponse;
};

export type PromoteListItemsResponse2 = PromoteListItemsResponses[keyof PromoteListItemsResponses];

export type SkipPromotionData = {
    body: SkipPromotionRequest;
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/promote/skip';
};

export type SkipPromotionErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type SkipPromotionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SkipPromotionResponse = SkipPromotionResponses[keyof SkipPromotionResponses];

export type ApplyBlueprintData = {
    body: ApplyBlueprintRequest;
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/apply-blueprint';
};

export type ApplyBlueprintErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type ApplyBlueprintResponses = {
    /**
     * OK
     */
    200: Array<ListItemResponse>;
};

export type ApplyBlueprintResponse = ApplyBlueprintResponses[keyof ApplyBlueprintResponses];

export type GetListRevisionData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/revision';
};

export type GetListRevisionErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetListRevisionResponses = {
    /**
     * OK
     */
    200: RevisionResponse;
};

export type GetListRevisionResponse = GetListRevisionResponses[keyof GetListRevisionResponses];

export type GetItemsData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items';
};

export type GetItemsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetItemsResponses = {
    /**
     * OK
     */
    200: Array<ListItemResponse>;
};

export type GetItemsResponse = GetItemsResponses[keyof GetItemsResponses];

export type CreateItemData = {
    body: CreateItemRequest;
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items';
};

export type CreateItemErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
    /**
     * Created
     */
    201: ListItemResponse;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items/{itemId}';
};

export type DeleteItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteItemResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteItemResponse = DeleteItemResponses[keyof DeleteItemResponses];

export type GetItemData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items/{itemId}';
};

export type GetItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetItemResponses = {
    /**
     * OK
     */
    200: ListItemResponse;
};

export type GetItemResponse = GetItemResponses[keyof GetItemResponses];

export type UpdateItemData = {
    body: UpdateItemRequest;
    path: {
        householdId: number;
        listId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items/{itemId}';
};

export type UpdateItemErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateItemError = UpdateItemErrors[keyof UpdateItemErrors];

export type UpdateItemResponses = {
    /**
     * OK
     */
    200: ListItemResponse;
};

export type UpdateItemResponse = UpdateItemResponses[keyof UpdateItemResponses];

export type CreateMediaItemData = {
    body: {
        file: IFormFile;
    } & {
        type: ListItemType;
    } & {
        caption?: string;
    };
    path: {
        householdId: number;
        listId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items/media';
};

export type CreateMediaItemErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Payload Too Large
     */
    413: unknown;
};

export type CreateMediaItemError = CreateMediaItemErrors[keyof CreateMediaItemErrors];

export type CreateMediaItemResponses = {
    /**
     * Created
     */
    201: ListItemResponse;
};

export type CreateMediaItemResponse = CreateMediaItemResponses[keyof CreateMediaItemResponses];

export type GetItemFileData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items/{itemId}/file';
};

export type GetItemFileErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetItemFileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetItemThumbnailData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items/{itemId}/thumbnail';
};

export type GetItemThumbnailErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetItemThumbnailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RestoreItemData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items/{itemId}/restore';
};

export type RestoreItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type RestoreItemResponses = {
    /**
     * OK
     */
    200: ListItemResponse;
};

export type RestoreItemResponse = RestoreItemResponses[keyof RestoreItemResponses];

export type ToggleItemStatusData = {
    body?: never;
    path: {
        householdId: number;
        listId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items/{itemId}/toggle-status';
};

export type ToggleItemStatusErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type ToggleItemStatusResponses = {
    /**
     * OK
     */
    200: ListItemResponse;
};

export type ToggleItemStatusResponse = ToggleItemStatusResponses[keyof ToggleItemStatusResponses];

export type ReorderItemData = {
    body: ReorderItemRequest;
    path: {
        householdId: number;
        listId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/lists/{listId}/items/{itemId}/reorder';
};

export type ReorderItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type ReorderItemResponses = {
    /**
     * OK
     */
    200: ListItemResponse;
};

export type ReorderItemResponse = ReorderItemResponses[keyof ReorderItemResponses];

export type GetInventoriesData = {
    body?: never;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories';
};

export type GetInventoriesErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetInventoriesResponses = {
    /**
     * OK
     */
    200: Array<InventoryResponse>;
};

export type GetInventoriesResponse = GetInventoriesResponses[keyof GetInventoriesResponses];

export type CreateInventoryData = {
    body: CreateInventoryRequest;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories';
};

export type CreateInventoryErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateInventoryError = CreateInventoryErrors[keyof CreateInventoryErrors];

export type CreateInventoryResponses = {
    /**
     * Created
     */
    201: InventoryResponse;
};

export type CreateInventoryResponse = CreateInventoryResponses[keyof CreateInventoryResponses];

export type GetExpiryCalendarData = {
    body?: never;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/calendar';
};

export type GetExpiryCalendarErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetExpiryCalendarResponses = {
    /**
     * OK
     */
    200: Array<ExpiryCalendarItemResponse>;
};

export type GetExpiryCalendarResponse = GetExpiryCalendarResponses[keyof GetExpiryCalendarResponses];

export type GetExpiryCalendarRevisionData = {
    body?: never;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/calendar/revision';
};

export type GetExpiryCalendarRevisionErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetExpiryCalendarRevisionResponses = {
    /**
     * OK
     */
    200: RevisionResponse;
};

export type GetExpiryCalendarRevisionResponse = GetExpiryCalendarRevisionResponses[keyof GetExpiryCalendarRevisionResponses];

export type DeleteInventoryData = {
    body?: never;
    path: {
        householdId: number;
        inventoryId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}';
};

export type DeleteInventoryErrors = {
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteInventoryResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteInventoryResponse = DeleteInventoryResponses[keyof DeleteInventoryResponses];

export type GetInventoryData = {
    body?: never;
    path: {
        householdId: number;
        inventoryId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}';
};

export type GetInventoryErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetInventoryResponses = {
    /**
     * OK
     */
    200: InventoryResponse;
};

export type GetInventoryResponse = GetInventoryResponses[keyof GetInventoryResponses];

export type UpdateInventoryData = {
    body: UpdateInventoryRequest;
    path: {
        householdId: number;
        inventoryId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}';
};

export type UpdateInventoryErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateInventoryError = UpdateInventoryErrors[keyof UpdateInventoryErrors];

export type UpdateInventoryResponses = {
    /**
     * OK
     */
    200: InventoryResponse;
};

export type UpdateInventoryResponse = UpdateInventoryResponses[keyof UpdateInventoryResponses];

export type GetInventoryRevisionData = {
    body?: never;
    path: {
        householdId: number;
        inventoryId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/revision';
};

export type GetInventoryRevisionErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetInventoryRevisionResponses = {
    /**
     * OK
     */
    200: RevisionResponse;
};

export type GetInventoryRevisionResponse = GetInventoryRevisionResponses[keyof GetInventoryRevisionResponses];

export type GetInventoryItemsData = {
    body?: never;
    path: {
        householdId: number;
        inventoryId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/items';
};

export type GetInventoryItemsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetInventoryItemsResponses = {
    /**
     * OK
     */
    200: Array<InventoryItemResponse>;
};

export type GetInventoryItemsResponse = GetInventoryItemsResponses[keyof GetInventoryItemsResponses];

export type CreateInventoryItemData = {
    body: CreateInventoryItemRequest;
    path: {
        householdId: number;
        inventoryId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/items';
};

export type CreateInventoryItemErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateInventoryItemError = CreateInventoryItemErrors[keyof CreateInventoryItemErrors];

export type CreateInventoryItemResponses = {
    /**
     * Created
     */
    201: InventoryItemResponse;
};

export type CreateInventoryItemResponse = CreateInventoryItemResponses[keyof CreateInventoryItemResponses];

export type DeleteInventoryItemData = {
    body?: never;
    path: {
        householdId: number;
        inventoryId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/items/{itemId}';
};

export type DeleteInventoryItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteInventoryItemResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteInventoryItemResponse = DeleteInventoryItemResponses[keyof DeleteInventoryItemResponses];

export type UpdateInventoryItemData = {
    body: UpdateInventoryItemRequest;
    path: {
        householdId: number;
        inventoryId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/items/{itemId}';
};

export type UpdateInventoryItemErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateInventoryItemError = UpdateInventoryItemErrors[keyof UpdateInventoryItemErrors];

export type UpdateInventoryItemResponses = {
    /**
     * OK
     */
    200: InventoryItemResponse;
};

export type UpdateInventoryItemResponse = UpdateInventoryItemResponses[keyof UpdateInventoryItemResponses];

export type RestoreInventoryItemData = {
    body?: never;
    path: {
        householdId: number;
        inventoryId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/items/{itemId}/restore';
};

export type RestoreInventoryItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type RestoreInventoryItemResponses = {
    /**
     * OK
     */
    200: InventoryItemResponse;
};

export type RestoreInventoryItemResponse = RestoreInventoryItemResponses[keyof RestoreInventoryItemResponses];

export type ReorderInventoryItemData = {
    body: ReorderItemRequest;
    path: {
        householdId: number;
        inventoryId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/items/{itemId}/reorder';
};

export type ReorderInventoryItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type ReorderInventoryItemResponses = {
    /**
     * OK
     */
    200: InventoryItemResponse;
};

export type ReorderInventoryItemResponse = ReorderInventoryItemResponses[keyof ReorderInventoryItemResponses];

export type GetInventorySettingsData = {
    body?: never;
    path: {
        householdId: number;
        inventoryId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/settings';
};

export type GetInventorySettingsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetInventorySettingsResponses = {
    /**
     * OK
     */
    200: InventorySettingsResponse;
};

export type GetInventorySettingsResponse = GetInventorySettingsResponses[keyof GetInventorySettingsResponses];

export type UpdateInventorySettingsData = {
    body: UpdateInventorySettingsRequest;
    path: {
        householdId: number;
        inventoryId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/settings';
};

export type UpdateInventorySettingsErrors = {
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateInventorySettingsResponses = {
    /**
     * OK
     */
    200: InventorySettingsResponse;
};

export type UpdateInventorySettingsResponse = UpdateInventorySettingsResponses[keyof UpdateInventorySettingsResponses];

export type GetMyInventoryNotificationData = {
    body?: never;
    path: {
        householdId: number;
        inventoryId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/notifications';
};

export type GetMyInventoryNotificationErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMyInventoryNotificationResponses = {
    /**
     * OK
     */
    200: MyInventoryNotificationResponse;
};

export type GetMyInventoryNotificationResponse = GetMyInventoryNotificationResponses[keyof GetMyInventoryNotificationResponses];

export type UpdateMyInventoryNotificationData = {
    body: UpdateMyInventoryNotificationRequest;
    path: {
        householdId: number;
        inventoryId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/inventories/{inventoryId}/notifications';
};

export type UpdateMyInventoryNotificationErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateMyInventoryNotificationError = UpdateMyInventoryNotificationErrors[keyof UpdateMyInventoryNotificationErrors];

export type UpdateMyInventoryNotificationResponses = {
    /**
     * OK
     */
    200: MyInventoryNotificationResponse;
};

export type UpdateMyInventoryNotificationResponse = UpdateMyInventoryNotificationResponses[keyof UpdateMyInventoryNotificationResponses];

export type GetRecipesData = {
    body?: never;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes';
};

export type GetRecipesErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRecipesResponses = {
    /**
     * OK
     */
    200: Array<RecipeResponse>;
};

export type GetRecipesResponse = GetRecipesResponses[keyof GetRecipesResponses];

export type CreateRecipeData = {
    body: CreateRecipeRequest;
    path: {
        householdId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes';
};

export type CreateRecipeErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateRecipeError = CreateRecipeErrors[keyof CreateRecipeErrors];

export type CreateRecipeResponses = {
    /**
     * Created
     */
    201: RecipeResponse;
};

export type CreateRecipeResponse = CreateRecipeResponses[keyof CreateRecipeResponses];

export type DeleteRecipeData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}';
};

export type DeleteRecipeErrors = {
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteRecipeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRecipeResponse = DeleteRecipeResponses[keyof DeleteRecipeResponses];

export type GetRecipeData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}';
};

export type GetRecipeErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRecipeResponses = {
    /**
     * OK
     */
    200: RecipeResponse;
};

export type GetRecipeResponse = GetRecipeResponses[keyof GetRecipeResponses];

export type UpdateRecipeData = {
    body: UpdateRecipeRequest;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}';
};

export type UpdateRecipeErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateRecipeError = UpdateRecipeErrors[keyof UpdateRecipeErrors];

export type UpdateRecipeResponses = {
    /**
     * OK
     */
    200: RecipeResponse;
};

export type UpdateRecipeResponse = UpdateRecipeResponses[keyof UpdateRecipeResponses];

export type GetRecipeRevisionData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/revision';
};

export type GetRecipeRevisionErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRecipeRevisionResponses = {
    /**
     * OK
     */
    200: RevisionResponse;
};

export type GetRecipeRevisionResponse = GetRecipeRevisionResponses[keyof GetRecipeRevisionResponses];

export type CopyRecipeToListData = {
    body: CopyRecipeToListRequest;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/copy-to-list';
};

export type CopyRecipeToListErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type CopyRecipeToListError = CopyRecipeToListErrors[keyof CopyRecipeToListErrors];

export type CopyRecipeToListResponses = {
    /**
     * OK
     */
    200: CopyRecipeToListResponse;
};

export type CopyRecipeToListResponse2 = CopyRecipeToListResponses[keyof CopyRecipeToListResponses];

export type SetRecipeTagsData = {
    body: SetRecipeTagsRequest;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/tags';
};

export type SetRecipeTagsErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type SetRecipeTagsError = SetRecipeTagsErrors[keyof SetRecipeTagsErrors];

export type SetRecipeTagsResponses = {
    /**
     * OK
     */
    200: RecipeResponse;
};

export type SetRecipeTagsResponse = SetRecipeTagsResponses[keyof SetRecipeTagsResponses];

export type SuggestRecipeTagsData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/suggest-tags';
};

export type SuggestRecipeTagsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type SuggestRecipeTagsResponses = {
    /**
     * OK
     */
    200: SuggestRecipeTagsResponse;
};

export type SuggestRecipeTagsResponse2 = SuggestRecipeTagsResponses[keyof SuggestRecipeTagsResponses];

export type GetRecipeItemsData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/items';
};

export type GetRecipeItemsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRecipeItemsResponses = {
    /**
     * OK
     */
    200: Array<RecipeItemResponse>;
};

export type GetRecipeItemsResponse = GetRecipeItemsResponses[keyof GetRecipeItemsResponses];

export type CreateRecipeItemData = {
    body: CreateRecipeItemRequest;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/items';
};

export type CreateRecipeItemErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateRecipeItemError = CreateRecipeItemErrors[keyof CreateRecipeItemErrors];

export type CreateRecipeItemResponses = {
    /**
     * Created
     */
    201: RecipeItemResponse;
};

export type CreateRecipeItemResponse = CreateRecipeItemResponses[keyof CreateRecipeItemResponses];

export type DeleteRecipeItemData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/items/{itemId}';
};

export type DeleteRecipeItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteRecipeItemResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRecipeItemResponse = DeleteRecipeItemResponses[keyof DeleteRecipeItemResponses];

export type GetRecipeItemData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/items/{itemId}';
};

export type GetRecipeItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRecipeItemResponses = {
    /**
     * OK
     */
    200: RecipeItemResponse;
};

export type GetRecipeItemResponse = GetRecipeItemResponses[keyof GetRecipeItemResponses];

export type UpdateRecipeItemData = {
    body: UpdateRecipeItemRequest;
    path: {
        householdId: number;
        recipeId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/items/{itemId}';
};

export type UpdateRecipeItemErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateRecipeItemError = UpdateRecipeItemErrors[keyof UpdateRecipeItemErrors];

export type UpdateRecipeItemResponses = {
    /**
     * OK
     */
    200: RecipeItemResponse;
};

export type UpdateRecipeItemResponse = UpdateRecipeItemResponses[keyof UpdateRecipeItemResponses];

export type RestoreRecipeItemData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/items/{itemId}/restore';
};

export type RestoreRecipeItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type RestoreRecipeItemResponses = {
    /**
     * OK
     */
    200: RecipeItemResponse;
};

export type RestoreRecipeItemResponse = RestoreRecipeItemResponses[keyof RestoreRecipeItemResponses];

export type ReorderRecipeItemData = {
    body: ReorderItemRequest;
    path: {
        householdId: number;
        recipeId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/items/{itemId}/reorder';
};

export type ReorderRecipeItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type ReorderRecipeItemResponses = {
    /**
     * OK
     */
    200: RecipeItemResponse;
};

export type ReorderRecipeItemResponse = ReorderRecipeItemResponses[keyof ReorderRecipeItemResponses];

export type GetRecipeSectionsData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/sections';
};

export type GetRecipeSectionsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRecipeSectionsResponses = {
    /**
     * OK
     */
    200: Array<RecipeSectionResponse>;
};

export type GetRecipeSectionsResponse = GetRecipeSectionsResponses[keyof GetRecipeSectionsResponses];

export type CreateRecipeSectionData = {
    body: CreateRecipeSectionRequest;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/sections';
};

export type CreateRecipeSectionErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateRecipeSectionError = CreateRecipeSectionErrors[keyof CreateRecipeSectionErrors];

export type CreateRecipeSectionResponses = {
    /**
     * Created
     */
    201: RecipeSectionResponse;
};

export type CreateRecipeSectionResponse = CreateRecipeSectionResponses[keyof CreateRecipeSectionResponses];

export type DeleteRecipeSectionData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        sectionId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/sections/{sectionId}';
};

export type DeleteRecipeSectionErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteRecipeSectionError = DeleteRecipeSectionErrors[keyof DeleteRecipeSectionErrors];

export type DeleteRecipeSectionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRecipeSectionResponse = DeleteRecipeSectionResponses[keyof DeleteRecipeSectionResponses];

export type UpdateRecipeSectionData = {
    body: UpdateRecipeSectionRequest;
    path: {
        householdId: number;
        recipeId: number;
        sectionId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/sections/{sectionId}';
};

export type UpdateRecipeSectionErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateRecipeSectionError = UpdateRecipeSectionErrors[keyof UpdateRecipeSectionErrors];

export type UpdateRecipeSectionResponses = {
    /**
     * OK
     */
    200: RecipeSectionResponse;
};

export type UpdateRecipeSectionResponse = UpdateRecipeSectionResponses[keyof UpdateRecipeSectionResponses];

export type RestoreRecipeSectionData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        sectionId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/sections/{sectionId}/restore';
};

export type RestoreRecipeSectionErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type RestoreRecipeSectionResponses = {
    /**
     * OK
     */
    200: RecipeSectionResponse;
};

export type RestoreRecipeSectionResponse = RestoreRecipeSectionResponses[keyof RestoreRecipeSectionResponses];

export type ReorderRecipeSectionData = {
    body: ReorderItemRequest;
    path: {
        householdId: number;
        recipeId: number;
        sectionId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/sections/{sectionId}/reorder';
};

export type ReorderRecipeSectionErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type ReorderRecipeSectionResponses = {
    /**
     * OK
     */
    200: RecipeSectionResponse;
};

export type ReorderRecipeSectionResponse = ReorderRecipeSectionResponses[keyof ReorderRecipeSectionResponses];

export type GetRecipeLinksData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/links';
};

export type GetRecipeLinksErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRecipeLinksResponses = {
    /**
     * OK
     */
    200: Array<RecipeLinkResponse>;
};

export type GetRecipeLinksResponse = GetRecipeLinksResponses[keyof GetRecipeLinksResponses];

export type CreateRecipeLinkData = {
    body: CreateRecipeLinkRequest;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/links';
};

export type CreateRecipeLinkErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateRecipeLinkError = CreateRecipeLinkErrors[keyof CreateRecipeLinkErrors];

export type CreateRecipeLinkResponses = {
    /**
     * Created
     */
    201: RecipeLinkResponse;
};

export type CreateRecipeLinkResponse = CreateRecipeLinkResponses[keyof CreateRecipeLinkResponses];

export type DeleteRecipeLinkData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        linkId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/links/{linkId}';
};

export type DeleteRecipeLinkErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteRecipeLinkResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRecipeLinkResponse = DeleteRecipeLinkResponses[keyof DeleteRecipeLinkResponses];

export type UpdateRecipeLinkData = {
    body: UpdateRecipeLinkRequest;
    path: {
        householdId: number;
        recipeId: number;
        linkId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/links/{linkId}';
};

export type UpdateRecipeLinkErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateRecipeLinkError = UpdateRecipeLinkErrors[keyof UpdateRecipeLinkErrors];

export type UpdateRecipeLinkResponses = {
    /**
     * OK
     */
    200: RecipeLinkResponse;
};

export type UpdateRecipeLinkResponse = UpdateRecipeLinkResponses[keyof UpdateRecipeLinkResponses];

export type RestoreRecipeLinkData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        linkId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/links/{linkId}/restore';
};

export type RestoreRecipeLinkErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type RestoreRecipeLinkResponses = {
    /**
     * OK
     */
    200: RecipeLinkResponse;
};

export type RestoreRecipeLinkResponse = RestoreRecipeLinkResponses[keyof RestoreRecipeLinkResponses];

export type ReorderRecipeLinkData = {
    body: ReorderItemRequest;
    path: {
        householdId: number;
        recipeId: number;
        linkId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/links/{linkId}/reorder';
};

export type ReorderRecipeLinkErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type ReorderRecipeLinkResponses = {
    /**
     * OK
     */
    200: RecipeLinkResponse;
};

export type ReorderRecipeLinkResponse = ReorderRecipeLinkResponses[keyof ReorderRecipeLinkResponses];

export type GetRecipeAttachmentsData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/attachments';
};

export type GetRecipeAttachmentsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRecipeAttachmentsResponses = {
    /**
     * OK
     */
    200: Array<RecipeAttachmentResponse>;
};

export type GetRecipeAttachmentsResponse = GetRecipeAttachmentsResponses[keyof GetRecipeAttachmentsResponses];

export type CreateRecipeAttachmentData = {
    body: {
        file: IFormFile;
    } & {
        caption?: string;
    };
    path: {
        householdId: number;
        recipeId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/attachments';
};

export type CreateRecipeAttachmentErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Payload Too Large
     */
    413: unknown;
};

export type CreateRecipeAttachmentError = CreateRecipeAttachmentErrors[keyof CreateRecipeAttachmentErrors];

export type CreateRecipeAttachmentResponses = {
    /**
     * Created
     */
    201: RecipeAttachmentResponse;
};

export type CreateRecipeAttachmentResponse = CreateRecipeAttachmentResponses[keyof CreateRecipeAttachmentResponses];

export type DeleteRecipeAttachmentData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        attachmentId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/attachments/{attachmentId}';
};

export type DeleteRecipeAttachmentErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteRecipeAttachmentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRecipeAttachmentResponse = DeleteRecipeAttachmentResponses[keyof DeleteRecipeAttachmentResponses];

export type UpdateRecipeAttachmentData = {
    body: UpdateRecipeAttachmentRequest;
    path: {
        householdId: number;
        recipeId: number;
        attachmentId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/attachments/{attachmentId}';
};

export type UpdateRecipeAttachmentErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type UpdateRecipeAttachmentError = UpdateRecipeAttachmentErrors[keyof UpdateRecipeAttachmentErrors];

export type UpdateRecipeAttachmentResponses = {
    /**
     * OK
     */
    200: RecipeAttachmentResponse;
};

export type UpdateRecipeAttachmentResponse = UpdateRecipeAttachmentResponses[keyof UpdateRecipeAttachmentResponses];

export type RestoreRecipeAttachmentData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        attachmentId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/attachments/{attachmentId}/restore';
};

export type RestoreRecipeAttachmentErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type RestoreRecipeAttachmentResponses = {
    /**
     * OK
     */
    200: RecipeAttachmentResponse;
};

export type RestoreRecipeAttachmentResponse = RestoreRecipeAttachmentResponses[keyof RestoreRecipeAttachmentResponses];

export type ReorderRecipeAttachmentData = {
    body: ReorderItemRequest;
    path: {
        householdId: number;
        recipeId: number;
        attachmentId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/attachments/{attachmentId}/reorder';
};

export type ReorderRecipeAttachmentErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type ReorderRecipeAttachmentResponses = {
    /**
     * OK
     */
    200: RecipeAttachmentResponse;
};

export type ReorderRecipeAttachmentResponse = ReorderRecipeAttachmentResponses[keyof ReorderRecipeAttachmentResponses];

export type GetRecipeAttachmentFileData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        attachmentId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/attachments/{attachmentId}/file';
};

export type GetRecipeAttachmentFileErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRecipeAttachmentFileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRecipeAttachmentThumbnailData = {
    body?: never;
    path: {
        householdId: number;
        recipeId: number;
        attachmentId: number;
    };
    query?: never;
    url: '/api/household/{householdId}/recipes/{recipeId}/attachments/{attachmentId}/thumbnail';
};

export type GetRecipeAttachmentThumbnailErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetRecipeAttachmentThumbnailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetActiveHouseholdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/active-household';
};

export type GetActiveHouseholdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetActiveHouseholdResponses = {
    /**
     * OK
     */
    200: ActiveHouseholdResponse;
};

export type GetActiveHouseholdResponse = GetActiveHouseholdResponses[keyof GetActiveHouseholdResponses];

export type SetActiveHouseholdData = {
    body: SetActiveHouseholdRequest;
    path?: never;
    query?: never;
    url: '/api/me/active-household';
};

export type SetActiveHouseholdErrors = {
    /**
     * Forbidden
     */
    403: unknown;
};

export type SetActiveHouseholdResponses = {
    /**
     * OK
     */
    200: ActiveHouseholdResponse;
};

export type SetActiveHouseholdResponse = SetActiveHouseholdResponses[keyof SetActiveHouseholdResponses];

export type GetUserSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/settings';
};

export type GetUserSettingsResponses = {
    /**
     * OK
     */
    200: UserSettingsResponse;
};

export type GetUserSettingsResponse = GetUserSettingsResponses[keyof GetUserSettingsResponses];

export type UpdateUserSettingsData = {
    body: UpdateUserSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/me/settings';
};

export type UpdateUserSettingsErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type UpdateUserSettingsError = UpdateUserSettingsErrors[keyof UpdateUserSettingsErrors];

export type UpdateUserSettingsResponses = {
    /**
     * OK
     */
    200: UserSettingsResponse;
};

export type UpdateUserSettingsResponse = UpdateUserSettingsResponses[keyof UpdateUserSettingsResponses];

export type UpdateUserNotificationSettingsData = {
    body: UpdateUserNotificationSettingsRequest;
    path?: never;
    query?: never;
    url: '/api/me/settings/notifications';
};

export type UpdateUserNotificationSettingsErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type UpdateUserNotificationSettingsError = UpdateUserNotificationSettingsErrors[keyof UpdateUserNotificationSettingsErrors];

export type UpdateUserNotificationSettingsResponses = {
    /**
     * OK
     */
    200: UserSettingsResponse;
};

export type UpdateUserNotificationSettingsResponse = UpdateUserNotificationSettingsResponses[keyof UpdateUserNotificationSettingsResponses];

export type UnregisterFcmTokenData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/api/notifications/token';
};

export type UnregisterFcmTokenResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UnregisterFcmTokenResponse = UnregisterFcmTokenResponses[keyof UnregisterFcmTokenResponses];

export type RegisterFcmTokenData = {
    body: RegisterFcmTokenRequest;
    path?: never;
    query?: never;
    url: '/api/notifications/token';
};

export type RegisterFcmTokenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWeatherForecastData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/WeatherForecast';
};

export type GetWeatherForecastResponses = {
    /**
     * OK
     */
    200: Array<WeatherForecast>;
};

export type GetWeatherForecastResponse = GetWeatherForecastResponses[keyof GetWeatherForecastResponses];

export type GetApiAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/me';
};

export type GetApiAuthMeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAuthProfileData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/profile';
};

export type PutApiAuthProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiDemoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Demo';
};

export type GetApiDemoResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiDemoResponse = GetApiDemoResponses[keyof GetApiDemoResponses];
