// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addMember, compactInventoryItems, compactItems, createHousehold, createInventory, createInventoryItem, createItem, createList, deleteHousehold, deleteInventory, deleteInventoryItem, deleteItem, deleteList, getActiveHousehold, getApiAuthMe, getApiDemo, getInventories, getInventory, getInventoryItems, getItem, getItems, getList, getLists, getMembers, getUserHouseholds, getWeatherForecast, type Options, putApiAuthProfile, removeMember, reorderInventoryItem, reorderItem, restoreInventoryItem, restoreItem, setActiveHousehold, toggleItemStatus, updateInventory, updateInventoryItem, updateItem, updateList, updateMemberRole } from '../sdk.gen';
import type { AddMemberData, AddMemberError, AddMemberResponse, CompactInventoryItemsData, CompactInventoryItemsResponse, CompactItemsData, CompactItemsResponse, CreateHouseholdData, CreateHouseholdError, CreateHouseholdResponse, CreateInventoryData, CreateInventoryError, CreateInventoryItemData, CreateInventoryItemError, CreateInventoryItemResponse, CreateInventoryResponse, CreateItemData, CreateItemError, CreateItemResponse, CreateListData, CreateListError, CreateListResponse, DeleteHouseholdData, DeleteHouseholdResponse, DeleteInventoryData, DeleteInventoryItemData, DeleteInventoryItemResponse, DeleteInventoryResponse, DeleteItemData, DeleteItemResponse, DeleteListData, DeleteListResponse, GetActiveHouseholdData, GetActiveHouseholdResponse, GetApiAuthMeData, GetApiDemoData, GetApiDemoResponse, GetInventoriesData, GetInventoriesResponse, GetInventoryData, GetInventoryItemsData, GetInventoryItemsResponse, GetInventoryResponse, GetItemData, GetItemResponse, GetItemsData, GetItemsResponse, GetListData, GetListResponse, GetListsData, GetListsResponse, GetMembersData, GetMembersResponse, GetUserHouseholdsData, GetUserHouseholdsResponse, GetWeatherForecastData, GetWeatherForecastResponse, PutApiAuthProfileData, RemoveMemberData, RemoveMemberError, RemoveMemberResponse, ReorderInventoryItemData, ReorderInventoryItemResponse, ReorderItemData, ReorderItemResponse, RestoreInventoryItemData, RestoreInventoryItemResponse, RestoreItemData, RestoreItemResponse, SetActiveHouseholdData, SetActiveHouseholdResponse, ToggleItemStatusData, ToggleItemStatusResponse, UpdateInventoryData, UpdateInventoryError, UpdateInventoryItemData, UpdateInventoryItemError, UpdateInventoryItemResponse, UpdateInventoryResponse, UpdateItemData, UpdateItemError, UpdateItemResponse, UpdateListData, UpdateListError, UpdateListResponse, UpdateMemberRoleData, UpdateMemberRoleError, UpdateMemberRoleResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getUserHouseholdsQueryKey = (options?: Options<GetUserHouseholdsData>) => createQueryKey('getUserHouseholds', options, false, ['Households']);

export const getUserHouseholdsOptions = (options?: Options<GetUserHouseholdsData>) => queryOptions<GetUserHouseholdsResponse, DefaultError, GetUserHouseholdsResponse, ReturnType<typeof getUserHouseholdsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserHouseholds({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserHouseholdsQueryKey(options)
});

export const createHouseholdMutation = (options?: Partial<Options<CreateHouseholdData>>): UseMutationOptions<CreateHouseholdResponse, CreateHouseholdError, Options<CreateHouseholdData>> => {
    const mutationOptions: UseMutationOptions<CreateHouseholdResponse, CreateHouseholdError, Options<CreateHouseholdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createHousehold({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteHouseholdMutation = (options?: Partial<Options<DeleteHouseholdData>>): UseMutationOptions<DeleteHouseholdResponse, DefaultError, Options<DeleteHouseholdData>> => {
    const mutationOptions: UseMutationOptions<DeleteHouseholdResponse, DefaultError, Options<DeleteHouseholdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteHousehold({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMembersQueryKey = (options: Options<GetMembersData>) => createQueryKey('getMembers', options, false, ['Members']);

export const getMembersOptions = (options: Options<GetMembersData>) => queryOptions<GetMembersResponse, DefaultError, GetMembersResponse, ReturnType<typeof getMembersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMembers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMembersQueryKey(options)
});

export const addMemberMutation = (options?: Partial<Options<AddMemberData>>): UseMutationOptions<AddMemberResponse, AddMemberError, Options<AddMemberData>> => {
    const mutationOptions: UseMutationOptions<AddMemberResponse, AddMemberError, Options<AddMemberData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addMember({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const removeMemberMutation = (options?: Partial<Options<RemoveMemberData>>): UseMutationOptions<RemoveMemberResponse, RemoveMemberError, Options<RemoveMemberData>> => {
    const mutationOptions: UseMutationOptions<RemoveMemberResponse, RemoveMemberError, Options<RemoveMemberData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeMember({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateMemberRoleMutation = (options?: Partial<Options<UpdateMemberRoleData>>): UseMutationOptions<UpdateMemberRoleResponse, UpdateMemberRoleError, Options<UpdateMemberRoleData>> => {
    const mutationOptions: UseMutationOptions<UpdateMemberRoleResponse, UpdateMemberRoleError, Options<UpdateMemberRoleData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateMemberRole({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getListsQueryKey = (options: Options<GetListsData>) => createQueryKey('getLists', options, false, ['Lists']);

export const getListsOptions = (options: Options<GetListsData>) => queryOptions<GetListsResponse, DefaultError, GetListsResponse, ReturnType<typeof getListsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLists({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getListsQueryKey(options)
});

export const createListMutation = (options?: Partial<Options<CreateListData>>): UseMutationOptions<CreateListResponse, CreateListError, Options<CreateListData>> => {
    const mutationOptions: UseMutationOptions<CreateListResponse, CreateListError, Options<CreateListData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createList({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteListMutation = (options?: Partial<Options<DeleteListData>>): UseMutationOptions<DeleteListResponse, DefaultError, Options<DeleteListData>> => {
    const mutationOptions: UseMutationOptions<DeleteListResponse, DefaultError, Options<DeleteListData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteList({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getListQueryKey = (options: Options<GetListData>) => createQueryKey('getList', options, false, ['Lists']);

export const getListOptions = (options: Options<GetListData>) => queryOptions<GetListResponse, DefaultError, GetListResponse, ReturnType<typeof getListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getListQueryKey(options)
});

export const updateListMutation = (options?: Partial<Options<UpdateListData>>): UseMutationOptions<UpdateListResponse, UpdateListError, Options<UpdateListData>> => {
    const mutationOptions: UseMutationOptions<UpdateListResponse, UpdateListError, Options<UpdateListData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateList({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getItemsQueryKey = (options: Options<GetItemsData>) => createQueryKey('getItems', options, false, ['ListItems']);

export const getItemsOptions = (options: Options<GetItemsData>) => queryOptions<GetItemsResponse, DefaultError, GetItemsResponse, ReturnType<typeof getItemsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getItems({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getItemsQueryKey(options)
});

export const createItemMutation = (options?: Partial<Options<CreateItemData>>): UseMutationOptions<CreateItemResponse, CreateItemError, Options<CreateItemData>> => {
    const mutationOptions: UseMutationOptions<CreateItemResponse, CreateItemError, Options<CreateItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteItemMutation = (options?: Partial<Options<DeleteItemData>>): UseMutationOptions<DeleteItemResponse, DefaultError, Options<DeleteItemData>> => {
    const mutationOptions: UseMutationOptions<DeleteItemResponse, DefaultError, Options<DeleteItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getItemQueryKey = (options: Options<GetItemData>) => createQueryKey('getItem', options, false, ['ListItems']);

export const getItemOptions = (options: Options<GetItemData>) => queryOptions<GetItemResponse, DefaultError, GetItemResponse, ReturnType<typeof getItemQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getItem({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getItemQueryKey(options)
});

export const updateItemMutation = (options?: Partial<Options<UpdateItemData>>): UseMutationOptions<UpdateItemResponse, UpdateItemError, Options<UpdateItemData>> => {
    const mutationOptions: UseMutationOptions<UpdateItemResponse, UpdateItemError, Options<UpdateItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const restoreItemMutation = (options?: Partial<Options<RestoreItemData>>): UseMutationOptions<RestoreItemResponse, DefaultError, Options<RestoreItemData>> => {
    const mutationOptions: UseMutationOptions<RestoreItemResponse, DefaultError, Options<RestoreItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await restoreItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const toggleItemStatusMutation = (options?: Partial<Options<ToggleItemStatusData>>): UseMutationOptions<ToggleItemStatusResponse, DefaultError, Options<ToggleItemStatusData>> => {
    const mutationOptions: UseMutationOptions<ToggleItemStatusResponse, DefaultError, Options<ToggleItemStatusData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await toggleItemStatus({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const reorderItemMutation = (options?: Partial<Options<ReorderItemData>>): UseMutationOptions<ReorderItemResponse, DefaultError, Options<ReorderItemData>> => {
    const mutationOptions: UseMutationOptions<ReorderItemResponse, DefaultError, Options<ReorderItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reorderItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const compactItemsMutation = (options?: Partial<Options<CompactItemsData>>): UseMutationOptions<CompactItemsResponse, DefaultError, Options<CompactItemsData>> => {
    const mutationOptions: UseMutationOptions<CompactItemsResponse, DefaultError, Options<CompactItemsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await compactItems({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getInventoriesQueryKey = (options: Options<GetInventoriesData>) => createQueryKey('getInventories', options, false, ['Inventories']);

export const getInventoriesOptions = (options: Options<GetInventoriesData>) => queryOptions<GetInventoriesResponse, DefaultError, GetInventoriesResponse, ReturnType<typeof getInventoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getInventories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getInventoriesQueryKey(options)
});

export const createInventoryMutation = (options?: Partial<Options<CreateInventoryData>>): UseMutationOptions<CreateInventoryResponse, CreateInventoryError, Options<CreateInventoryData>> => {
    const mutationOptions: UseMutationOptions<CreateInventoryResponse, CreateInventoryError, Options<CreateInventoryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createInventory({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteInventoryMutation = (options?: Partial<Options<DeleteInventoryData>>): UseMutationOptions<DeleteInventoryResponse, DefaultError, Options<DeleteInventoryData>> => {
    const mutationOptions: UseMutationOptions<DeleteInventoryResponse, DefaultError, Options<DeleteInventoryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteInventory({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getInventoryQueryKey = (options: Options<GetInventoryData>) => createQueryKey('getInventory', options, false, ['Inventories']);

export const getInventoryOptions = (options: Options<GetInventoryData>) => queryOptions<GetInventoryResponse, DefaultError, GetInventoryResponse, ReturnType<typeof getInventoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getInventory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getInventoryQueryKey(options)
});

export const updateInventoryMutation = (options?: Partial<Options<UpdateInventoryData>>): UseMutationOptions<UpdateInventoryResponse, UpdateInventoryError, Options<UpdateInventoryData>> => {
    const mutationOptions: UseMutationOptions<UpdateInventoryResponse, UpdateInventoryError, Options<UpdateInventoryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateInventory({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getInventoryItemsQueryKey = (options: Options<GetInventoryItemsData>) => createQueryKey('getInventoryItems', options, false, ['InventoryItems']);

export const getInventoryItemsOptions = (options: Options<GetInventoryItemsData>) => queryOptions<GetInventoryItemsResponse, DefaultError, GetInventoryItemsResponse, ReturnType<typeof getInventoryItemsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getInventoryItems({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getInventoryItemsQueryKey(options)
});

export const createInventoryItemMutation = (options?: Partial<Options<CreateInventoryItemData>>): UseMutationOptions<CreateInventoryItemResponse, CreateInventoryItemError, Options<CreateInventoryItemData>> => {
    const mutationOptions: UseMutationOptions<CreateInventoryItemResponse, CreateInventoryItemError, Options<CreateInventoryItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createInventoryItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteInventoryItemMutation = (options?: Partial<Options<DeleteInventoryItemData>>): UseMutationOptions<DeleteInventoryItemResponse, DefaultError, Options<DeleteInventoryItemData>> => {
    const mutationOptions: UseMutationOptions<DeleteInventoryItemResponse, DefaultError, Options<DeleteInventoryItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteInventoryItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateInventoryItemMutation = (options?: Partial<Options<UpdateInventoryItemData>>): UseMutationOptions<UpdateInventoryItemResponse, UpdateInventoryItemError, Options<UpdateInventoryItemData>> => {
    const mutationOptions: UseMutationOptions<UpdateInventoryItemResponse, UpdateInventoryItemError, Options<UpdateInventoryItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateInventoryItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const restoreInventoryItemMutation = (options?: Partial<Options<RestoreInventoryItemData>>): UseMutationOptions<RestoreInventoryItemResponse, DefaultError, Options<RestoreInventoryItemData>> => {
    const mutationOptions: UseMutationOptions<RestoreInventoryItemResponse, DefaultError, Options<RestoreInventoryItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await restoreInventoryItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const reorderInventoryItemMutation = (options?: Partial<Options<ReorderInventoryItemData>>): UseMutationOptions<ReorderInventoryItemResponse, DefaultError, Options<ReorderInventoryItemData>> => {
    const mutationOptions: UseMutationOptions<ReorderInventoryItemResponse, DefaultError, Options<ReorderInventoryItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reorderInventoryItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const compactInventoryItemsMutation = (options?: Partial<Options<CompactInventoryItemsData>>): UseMutationOptions<CompactInventoryItemsResponse, DefaultError, Options<CompactInventoryItemsData>> => {
    const mutationOptions: UseMutationOptions<CompactInventoryItemsResponse, DefaultError, Options<CompactInventoryItemsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await compactInventoryItems({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getActiveHouseholdQueryKey = (options?: Options<GetActiveHouseholdData>) => createQueryKey('getActiveHousehold', options, false, ['Me']);

export const getActiveHouseholdOptions = (options?: Options<GetActiveHouseholdData>) => queryOptions<GetActiveHouseholdResponse, DefaultError, GetActiveHouseholdResponse, ReturnType<typeof getActiveHouseholdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getActiveHousehold({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getActiveHouseholdQueryKey(options)
});

export const setActiveHouseholdMutation = (options?: Partial<Options<SetActiveHouseholdData>>): UseMutationOptions<SetActiveHouseholdResponse, DefaultError, Options<SetActiveHouseholdData>> => {
    const mutationOptions: UseMutationOptions<SetActiveHouseholdResponse, DefaultError, Options<SetActiveHouseholdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await setActiveHousehold({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWeatherForecastQueryKey = (options?: Options<GetWeatherForecastData>) => createQueryKey('getWeatherForecast', options, false, ['WeatherForecast']);

export const getWeatherForecastOptions = (options?: Options<GetWeatherForecastData>) => queryOptions<GetWeatherForecastResponse, DefaultError, GetWeatherForecastResponse, ReturnType<typeof getWeatherForecastQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWeatherForecast({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWeatherForecastQueryKey(options)
});

export const getApiAuthMeQueryKey = (options?: Options<GetApiAuthMeData>) => createQueryKey('getApiAuthMe', options, false, ['Auth']);

export const getApiAuthMeOptions = (options?: Options<GetApiAuthMeData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiAuthMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAuthMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAuthMeQueryKey(options)
});

export const putApiAuthProfileMutation = (options?: Partial<Options<PutApiAuthProfileData>>): UseMutationOptions<unknown, DefaultError, Options<PutApiAuthProfileData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutApiAuthProfileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiAuthProfile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiDemoQueryKey = (options?: Options<GetApiDemoData>) => createQueryKey('getApiDemo', options, false, ['Demo']);

export const getApiDemoOptions = (options?: Options<GetApiDemoData>) => queryOptions<GetApiDemoResponse, DefaultError, GetApiDemoResponse, ReturnType<typeof getApiDemoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiDemo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiDemoQueryKey(options)
});
